import 'package:hive/hive.dart';

part 'user_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0)
class User {
  @HiveField(0)
  final int userId;

  @HiveField(1)
  final String username;

  @HiveField(2)
  final String phone;

  @HiveField(3)
  final String email;

  @HiveField(4)
  final String role;

  @HiveField(5)
  final bool status;

  User({
    required this.userId,
    required this.username,
    required this.phone,
    required this.email,
    required this.role,
    required this.status,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      userId: json['userId'],
      username: json['username'],
      phone: json['phone'],
      email: json['email'],
      role: json['role'],
      status: json['status'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'userId': userId,
      'username': username,
      'phone': phone,
      'email': email,
      'role': role,
      'status': status,
    };
  }
}
