// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBym8vT8bOIlAzVfhm0Gd_34vU6onTX-Co',
    appId: '1:443300820189:web:a7f8d03d77122636d19734',
    messagingSenderId: '443300820189',
    projectId: 'ride-sharing-c8fb1',
    authDomain: 'ride-sharing-c8fb1.firebaseapp.com',
    storageBucket: 'ride-sharing-c8fb1.appspot.com',
    measurementId: 'G-WN3FEYH5N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdWO95s44Y1WorBo1i1zbuFoQCTSvAgUs',
    appId: '1:443300820189:android:bebea42d4419fdcdd19734',
    messagingSenderId: '443300820189',
    projectId: 'ride-sharing-c8fb1',
    storageBucket: 'ride-sharing-c8fb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7gsIqKbN1EamKssP2MgZo4ZHBTEPjXBY',
    appId: '1:443300820189:ios:8a985564610d08a6d19734',
    messagingSenderId: '443300820189',
    projectId: 'ride-sharing-c8fb1',
    storageBucket: 'ride-sharing-c8fb1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7gsIqKbN1EamKssP2MgZo4ZHBTEPjXBY',
    appId: '1:443300820189:ios:8a985564610d08a6d19734',
    messagingSenderId: '443300820189',
    projectId: 'ride-sharing-c8fb1',
    storageBucket: 'ride-sharing-c8fb1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBym8vT8bOIlAzVfhm0Gd_34vU6onTX-Co',
    appId: '1:443300820189:web:2da839f5285c8c85d19734',
    messagingSenderId: '443300820189',
    projectId: 'ride-sharing-c8fb1',
    authDomain: 'ride-sharing-c8fb1.firebaseapp.com',
    storageBucket: 'ride-sharing-c8fb1.appspot.com',
    measurementId: 'G-PPRE94LV5K',
  );
}
